[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.4",
    "setuptools_scm_git_archive",
]

[project]
name = "{{ cookiecutter.project_name }}"
description = "{{ cookiecutter.project_short_description }}"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering"
]
dynamic = ["version"]

[tool.coverage.run]
branch = true

[tool.isort]
profile = "black"

[tool.mypy]
strict = {{ cookiecutter.mypy_strict.lower() }}

[tool.pydocstyle]
convention = "numpy"
add_ignore = "D1"

[tool.setuptools_scm]
write_to = "{{ cookiecutter.project_slug }}/version.py"
write_to_template = '''
# Do not change! Do not track in version control!
__version__ = "{version}"
'''
